### ISSUE TITLE
dead link to "software_to_install" in Hackathon-Checklist.md

### ISSUE THREAD

**Issue by etcadinfinitum** [UWB-ACM/Hackathon-Docs-2019#9]
Three options:

- Delete the link
- Link to external site with recommendations (probably best option)
- Create our own recommendation page with various software packages students might need (ngrok/jekyll, react, ???) (probably ideal option)

@Chris-Johnston your opinion would be useful

**Comment by Chris-Johnston** [comment]
I think the link had previously pointed at this? https://github.com/UWB-ACM/Hackathon-Docs-2018/blob/master/Installing-Software.md

But because this is a much broader subject, we should really just remove that link.
